{{- if and .Values.backend.cursorSecret (not .Values.backend.existingCursorSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cursor-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cursor-secret
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: server-scan
type: Opaque
stringData:
  cursor-secret: {{ .Values.backend.cursorSecret | quote }}
{{- end }}
