apiVersion: v1
kind: Service
metadata:
  name: server-inventory-api
  labels:
    app.kubernetes.io/name: server-inventory-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: server-inventory
spec:
  selector:
    app.kubernetes.io/name: server-inventory-api
  ports:
    - name: http
      port: 80
      targetPort: http
