apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server-inventory-api
  labels:
    app.kubernetes.io/name: server-inventory-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: server-inventory
spec:
  to:
    kind: Service
    name: server-inventory-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
